from __future__ import annotations

import re
import os
from dataclasses import dataclass
from typing import Any, Mapping, Optional

from pyclaw.core.artifact_verification import (
    ArtifactEvidence,
    ArtifactSpec,
    ArtifactVerifierRegistry,
    normalize_slide_for_similarity,
    topic_keyword_in_text,
    is_weak_slide_text,
)
from pyclaw.core.skill_manifest import path_has_matching_skill_manifest


# Backward-compatible public name used by the agent and existing tests.
ArtifactAcceptanceSpec = ArtifactSpec


@dataclass(frozen=True)
class ArtifactAcceptanceResult:
    """Result of checking pending file deliveries against the task contract."""

    accepted: bool
    evidence: tuple[ArtifactEvidence, ...] = ()
    accepted_paths: frozenset[str] = frozenset()
    reasons: tuple[str, ...] = ()
    summary: str = ""


class ArtifactAcceptanceService:
    """Compatibility adapter around the artifact verification layer.

    PyClaw's controller keeps the Hermes/OpenClaw-style ownership boundary:
    the model/tool layer may produce files, but this service infers a concrete
    artifact spec from the user task, dispatches to type-specific verifiers,
    and returns only evidence-backed accepted paths.
    """

    PPT_MARKERS = ("ppt", "pptx", "powerpoint", "slide", "slides", "deck", "幻灯片", "演示文稿")

    def __init__(self, registry: Optional[ArtifactVerifierRegistry] = None) -> None:
        self.registry = registry or ArtifactVerifierRegistry()

    def evaluate(self, contract: Any, pending_files: list[dict[str, Any]]) -> ArtifactAcceptanceResult:
        spec = self.infer_spec(str(getattr(contract, "task_text", "")))
        evidences: list[ArtifactEvidence] = []
        accepted_paths: set[str] = set()
        rejection_reasons: list[str] = []
        summaries: list[str] = []

        for item in pending_files:
            if not isinstance(item, Mapping):
                continue
            raw_path = str(item.get("file_path", "")).strip()
            if not raw_path:
                continue
            stale_reason = self._stale_artifact_reason(contract, raw_path)
            if stale_reason:
                rejection_reasons.append(stale_reason)
                evidences.append(self.registry.inspect(raw_path, spec))
                continue
            verification = self.registry.verify(spec, raw_path)
            evidences.append(verification.evidence)
            if verification.accepted:
                accepted_paths.add(verification.evidence.file_path)
                if verification.summary:
                    summaries.append(verification.summary)
            elif verification.reason:
                rejection_reasons.append(verification.reason)

        if not evidences:
            return ArtifactAcceptanceResult(False, (), frozenset(), ("未观察到待发送文件",), "未观察到待发送文件")

        if accepted_paths:
            return ArtifactAcceptanceResult(
                True,
                tuple(evidences),
                frozenset(accepted_paths),
                (),
                summaries[0] if summaries else self._accepted_summary(spec, [item for item in evidences if item.file_path in accepted_paths]),
            )
        return ArtifactAcceptanceResult(
            False,
            tuple(evidences),
            frozenset(),
            tuple(reason for reason in rejection_reasons if reason),
            "; ".join(reason for reason in rejection_reasons if reason),
        )

    def _stale_artifact_reason(self, contract: Any, file_path: str) -> str:
        """Reject stale files for explicit skill deliverables.

        Skill workflows are provenance-sensitive: a PPTX generated by an older
        turn must not satisfy a new request just because it lives in the same
        artifact directory.  Generic file deliverables keep the historic looser
        behavior for compatibility; explicit skill requests require fresh,
        turn-scoped artifacts.
        """
        if not getattr(contract, "required_skills", ()):  # type: ignore[attr-defined]
            return ""
        try:
            created_at = float(getattr(contract, "created_at", 0.0) or 0.0)
        except (TypeError, ValueError):
            created_at = 0.0
        if created_at <= 0:
            return ""
        normalized = os.path.abspath(os.path.expanduser(file_path))
        try:
            mtime = os.path.getmtime(normalized)
        except OSError:
            return ""
        if mtime + 0.001 < created_at:
            if path_has_matching_skill_manifest(normalized, contract):
                return ""
            name = os.path.basename(normalized)
            return f"{name}: 文件早于当前任务创建，不能作为本轮 skill 交付证据"
        return ""

    def infer_spec(self, task_text: str) -> ArtifactAcceptanceSpec:
        normalized = (task_text or "").lower()
        expected_kind = "pptx" if any(marker in normalized for marker in self.PPT_MARKERS) else ""
        if not expected_kind and any(
            marker in normalized
            for marker in ("html", "网页", "页面", "教学网页", "可视化网页", "website", "web page", "webpage")
        ):
            expected_kind = "html"
        min_slides = self._explicit_slide_count(task_text) if expected_kind == "pptx" else None
        topic_keywords = self._topic_keywords(task_text) if expected_kind in {"pptx", "html"} else ()
        html_requirements = self._html_requirements(task_text) if expected_kind == "html" else {}
        return ArtifactAcceptanceSpec(
            expected_kind=expected_kind,
            min_slides=min_slides,
            topic_keywords=topic_keywords,
            **html_requirements,
        )

    def inspect_pending_files(self, pending_files: list[dict[str, Any]]) -> list[ArtifactEvidence]:
        spec = ArtifactAcceptanceSpec()
        evidences: list[ArtifactEvidence] = []
        for item in pending_files:
            if not isinstance(item, Mapping):
                continue
            raw_path = str(item.get("file_path", "")).strip()
            if not raw_path:
                continue
            evidences.append(self.registry.inspect(raw_path, spec))
        return evidences

    def inspect_file(self, file_path: str) -> ArtifactEvidence:
        return self.registry.inspect(file_path, ArtifactAcceptanceSpec())

    def _accepted_summary(self, spec: ArtifactAcceptanceSpec, evidences: list[ArtifactEvidence]) -> str:
        if not evidences:
            return ""
        first = evidences[0]
        if spec.expected_kind == "pptx" and first.slide_count is not None:
            return f"PPTX 可打开，共 {first.slide_count} 页"
        import os
        return f"文件已验证：{os.path.basename(first.file_path)}"

    # Compatibility wrappers retained for tests and older integration code that
    # directly exercised the prior monolithic service internals.
    def _accepts_evidence(self, spec: ArtifactAcceptanceSpec, evidence: ArtifactEvidence) -> tuple[bool, str]:
        result = self.registry.verify_evidence(spec, evidence)
        return result.accepted, result.reason

    def _topic_keyword_in_text(self, keyword: str, normalized_text: str) -> bool:
        return topic_keyword_in_text(keyword, normalized_text)

    def _is_weak_slide_text(self, text: str) -> bool:
        return is_weak_slide_text(text)

    def _normalize_slide_for_similarity(self, text: str) -> str:
        return normalize_slide_for_similarity(text)

    def _topic_keywords(self, text: str) -> tuple[str, ...]:
        raw = (text or "").strip()
        if not raw:
            return ()
        topic = raw
        patterns = (
            r"关于\s*(.+?)\s*(?:的)?(?:ppt|pptx|幻灯片|演示文稿|slide|deck)",
            r"图解\s*(.+?)(?:结构|训练流程|训练|原理|流程|架构)",
            r"(?:网页|页面|website|webpage|web page).*?图解\s*(.+?)(?:结构|训练流程|训练|原理|流程|架构|$)",
            r"(?:做一个|生成|创建|制作|给我做|帮我做|出一个)\s*(?:可视化的?)?(?:教学)?(?:网页|页面)\s*[，,：:]?\s*(.+)$",
            r"about\s+(.+?)\s+(?:ppt|pptx|slides|deck)",
        )
        for pattern in patterns:
            match = re.search(pattern, raw, flags=re.IGNORECASE)
            if match:
                topic = match.group(1)
                break
        topic = re.sub(
            r"(?:做一个|生成|创建|制作|给我做|帮我做|出一个|可视化的?|教学|网页|页面|图解|结构|训练流程|训练|原理|流程|的|pptx?|幻灯片|演示文稿|slides?|deck)",
            " ",
            topic,
            flags=re.IGNORECASE,
        )
        tokens = re.findall(r"[A-Za-z][A-Za-z0-9_+-]*|[\u4e00-\u9fff]{2,}", topic)
        stopwords = {"关于", "一个", "这个", "那个", "文件", "主题"}
        keywords = []
        for token in tokens:
            cleaned = token.strip()
            if not cleaned or cleaned in stopwords:
                continue
            if cleaned.lower() not in {item.lower() for item in keywords}:
                keywords.append(cleaned)
        return tuple(keywords[:8])

    def _html_requirements(self, text: str) -> dict[str, Any]:
        raw = text or ""
        normalized = raw.lower()
        sections = self._explicit_html_sections(raw)
        markers: list[str] = []
        for marker in (
            "Tokenizer", "Transformer", "Q/K/V", "Pretraining", "SFT", "RLHF",
            "Sampling", "Top-k", "Top-p", "Temperature", "Scaling Law", "术语表",
        ):
            if marker.lower() in normalized:
                markers.append(marker)
        return {
            "required_html_markers": tuple(self._dedupe_preserve_order(markers)),
            "required_html_sections": tuple(sections),
            "requires_tailwind_cdn": bool(re.search(r"tailwind\s*css|tailwindcss|tailwind\s*cdn", raw, flags=re.IGNORECASE)),
            "requires_tailwind_utilities": bool(re.search(r"tailwind\s+utility\s+class|utility\s+class|不要自己写大段\s*css", raw, flags=re.IGNORECASE)),
            "requires_chartjs_cdn": bool(re.search(r"chart\s*\.\s*js|chartjs|chart\s*js\s*cdn", raw, flags=re.IGNORECASE)),
            "requires_css_animation": bool(re.search(r"css\s*animation|css\s*动画|@keyframes|动画", raw, flags=re.IGNORECASE)),
            "requires_vanilla_js": bool(re.search(r"vanilla\s*js|原生\s*js|纯\s*js", raw, flags=re.IGNORECASE)),
            "requires_build_script": bool(re.search(r"build\.py|先写\s*build|生成脚本", raw, flags=re.IGNORECASE)),
            "requires_visual_polish": bool(re.search(
                r"精美|高级|漂亮|炫酷|高颜值|设计感|视觉效果|高质量.*(?:网页|页面)|(?:网页|页面).*高质量|polished\s*webpage|premium\s*webpage",
                raw,
                flags=re.IGNORECASE,
            )),
        }

    def _explicit_html_sections(self, text: str) -> list[str]:
        sections: list[str] = []
        for match in re.finditer(r"(?:^|[\n；;])\s*(\d{1,2})[.、)]\s*([^\n；;。]+)", text or ""):
            item = match.group(2).strip(" ：:，,。.;；")
            if item:
                sections.append(item[:80])
        sections.extend(self._explicit_multiline_html_sections(text or ""))
        board_match = None if sections else re.search(r"(?:板块|模块|章节)\s*[:：]\s*(.+?)(?:\n\s*\n|$)", text or "", flags=re.IGNORECASE | re.DOTALL)
        if board_match:
            tail = board_match.group(1)
            for item in re.split(r"[、,，；;\n]+", tail):
                cleaned = item.strip(" ：:，,。.;；")
                cleaned = re.sub(r"^\d{1,2}[.、)]\s*", "", cleaned)
                if self._is_delivery_instruction_fragment(cleaned):
                    continue
                if 1 <= len(cleaned) <= 80:
                    sections.append(cleaned)
        return self._dedupe_preserve_order(sections)[:24]

    def _explicit_multiline_html_sections(self, text: str) -> list[str]:
        sections: list[str] = []
        capture = False
        expected_count: int | None = None
        for raw_line in (text or "").splitlines():
            line = re.sub(r"\s+", " ", raw_line).strip()
            if not line:
                if capture and sections:
                    break
                continue
            if not capture:
                intro = re.search(r"(?:必须包含|包含以下|包含下列|以下|下列).{0,24}?(\d{1,2})\s*个?(?:板块|模块|章节|部分|section)", line, flags=re.IGNORECASE)
                if not intro:
                    continue
                expected_count = int(intro.group(1))
                capture = True
                parts = re.split(r"[:：]", line, maxsplit=1)
                if len(parts) == 1 or not parts[1].strip():
                    continue
                candidate = parts[1]
            else:
                candidate = line
            cleaned = re.sub(r"^[-*•]\s*", "", candidate).strip(" ：:，,。.;；")
            cleaned = re.sub(r"^\d{1,2}[.、)]\s*", "", cleaned).strip(" ：:，,。.;；")
            if not cleaned:
                continue
            if self._is_html_section_list_stop(cleaned) or self._is_delivery_instruction_fragment(cleaned):
                break
            if 1 <= len(cleaned) <= 140:
                sections.append(cleaned[:80])
            if expected_count is not None and len(sections) >= expected_count:
                break
        return sections

    def _is_html_section_list_stop(self, text: str) -> bool:
        normalized = (text or "").lower().strip()
        return any(marker in normalized for marker in (
            "硬性要求", "技术栈", "实现策略", "视觉风格", "交互", "页面自包含",
            "单个 html", "单个html", "必须通过 cdn", "必须通过cdn", "额外通过",
            "页面顶部", "最后用", "请直接", "不要先", "交付到", "保存到", "写到",
        ))

    def _is_delivery_instruction_fragment(self, text: str) -> bool:
        normalized = (text or "").lower()
        return any(marker in normalized for marker in ("send_file_to_user", "send-file-to-user", "交付给我", "发给我", "写到", "保存到"))

    def _dedupe_preserve_order(self, values: list[str]) -> list[str]:
        seen: set[str] = set()
        result: list[str] = []
        for value in values:
            key = re.sub(r"\s+", "", (value or "").lower())
            if not key or key in seen:
                continue
            seen.add(key)
            result.append(value)
        return result

    def _explicit_slide_count(self, text: str) -> Optional[int]:
        if not text:
            return None
        patterns = (
            r"(\d{1,3})\s*(?:页|頁|张|張|p\b|pages?\b|slides?\b)",
            r"(?:页数|頁數|slides?|pages?)\s*[:：]?\s*(\d{1,3})",
        )
        for pattern in patterns:
            match = re.search(pattern, text, flags=re.IGNORECASE)
            if match:
                value = int(match.group(1))
                if 1 <= value <= 300:
                    return value
        chinese = self._chinese_slide_count(text)
        return chinese

    def _chinese_slide_count(self, text: str) -> Optional[int]:
        digit = "零一二两三四五六七八九"
        pattern = rf"([{digit}十百]{{1,6}})\s*(?:页|頁|张|張)"
        match = re.search(pattern, text)
        if not match:
            return None
        value = self._parse_small_chinese_number(match.group(1))
        if value and 1 <= value <= 300:
            return value
        return None

    def _parse_small_chinese_number(self, text: str) -> int:
        values = {"零": 0, "一": 1, "二": 2, "两": 2, "三": 3, "四": 4, "五": 5, "六": 6, "七": 7, "八": 8, "九": 9}
        if not text:
            return 0
        if text == "十":
            return 10
        if "百" in text:
            left, _, right = text.partition("百")
            hundreds = values.get(left, 1 if not left else 0) * 100
            return hundreds + self._parse_small_chinese_number(right)
        if "十" in text:
            left, _, right = text.partition("十")
            tens = values.get(left, 1 if not left else 0) * 10
            ones = values.get(right, 0) if right else 0
            return tens + ones
        total = 0
        for ch in text:
            total = total * 10 + values.get(ch, 0)
        return total
