from __future__ import annotations

import os
import re
import shlex
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class LocalPathReference:
    """A shell-aware local filesystem reference found in a command.

    ``path`` is the token as generated by the model. ``resolved_path`` is the
    path resolved against the shell's current directory at that point in the
    command.  The extractor intentionally reports only arguments that are used
    by local filesystem commands/redirections; quoted remote commands and code
    strings are left opaque so Android/Linux paths such as ``/system/bin/sh`` or
    ``/proc/stat`` are not mistaken for host filesystem access.
    """

    path: str
    resolved_path: str
    reason: str


TERMINAL_INTENT_KEYWORDS: dict[str, tuple[str, ...]] = {
    "capture_screenshot": (
        "截屏", "截图", "屏幕截图", "截个屏", "screen shot", "screenshot", "screen capture",
    ),
    "capture_photo": (
        "拍照", "拍个照", "拍张照", "拍一张", "照相", "照一张", "摄像头", "相机", "自拍",
        "camera", "photo", "take a picture", "take photo",
    ),
    "record_screen": (
        "录屏", "屏幕录制", "录制屏幕", "screen record", "record screen", "screen recording",
    ),
    "notify": (
        "通知", "提醒", "弹窗", "notification", "notify", "remind", "alert",
    ),
    "open": (
        "打开", "浏览器", "页面", "网页", "open", "browser", "launch",
    ),
    "install": (
        "安装", "install", "npm install", "pip install", "brew install",
    ),
    "git_commit": (
        "代码提交", "提交代码", "提交", "commit",
    ),
    "git_push": (
        "push", "推送", "推到", "提交到github", "提交到 github",
    ),
    "process_control": (
        "停止进程", "杀进程", "kill", "pkill", "terminate process", "stop process",
    ),
    "file_mutation": (
        "创建", "新建", "写入", "保存", "复制", "移动", "改名", "mkdir", "touch", "copy", "move", "save",
    ),
}

BROAD_EXECUTION_KEYWORDS = (
    "执行", "运行", "跑一下", "跑", "开跑", "do it", "run it", "execute", "go ahead",
)

_SHELL_OPERATORS = {"&&", "||", ";", "|"}
_REDIRECT_OPERATORS = {">", ">>", "<"}
_FD_REDIRECT_OPERATORS = {">&", "<&"}

_LOCAL_PATH_COMMANDS = {
    "cd", "ls", "cat", "head", "tail", "wc", "file", "stat", "less", "more", "tree",
    "find", "grep", "egrep", "fgrep", "rg", "sed",
    "cp", "mv", "rm", "mkdir", "touch", "chmod", "chown",
    "python", "python3", "bash", "sh", "zsh", "node", "ruby", "perl",
}
_PATH_PASSTHROUGH_COMMANDS = {
    "cat", "head", "tail", "wc", "file", "stat", "less", "more", "tree",
    "cp", "mv", "rm", "mkdir", "touch", "chmod", "chown",
}
_SCRIPT_COMMANDS = {"python", "python3", "bash", "sh", "zsh", "node", "ruby", "perl"}

_REMOTE_CLI_HEADS = {"opencli", "ssh", "kubectl", "adb"}
_READ_ONLY_HEADS = {
    "pwd", "date", "echo", "printf", "true", "false", "test", "which", "command", "type",
    "rg", "grep", "egrep", "fgrep", "find", "sed", "head", "tail", "cat", "wc", "ls", "tree",
    "ioreg", "ps", "lsof", "df", "du", "stat", "file", "jq",
    "python", "python3",
}
_READ_LIKE_WORDS = {
    "get", "list", "show", "describe", "detail", "details", "info", "status", "current",
    "query", "search", "read", "inspect", "dump", "logs", "log", "tail", "cat", "help",
    "version", "check", "probe", "scan", "view", "print",
}
_MUTATE_LIKE_WORDS = {
    "create", "update", "delete", "remove", "rm", "write", "set", "apply", "patch",
    "edit", "modify", "install", "uninstall", "push", "commit", "send", "open", "start",
    "stop", "restart", "reboot", "kill", "exec", "run", "trigger", "launch", "copy", "move",
    "upload", "download",
}


def _tokenize_shell(command: str) -> list[str]:
    if not command:
        return []
    try:
        lexer = shlex.shlex(command, posix=True, punctuation_chars="|&;<>")
        lexer.whitespace_split = True
        return list(lexer)
    except ValueError:
        return []


def _split_shell_token_segments(command: str) -> list[list[str]]:
    tokens = _tokenize_shell(command)
    if not tokens:
        return []
    segments: list[list[str]] = []
    current: list[str] = []
    for token in tokens:
        if token in _SHELL_OPERATORS:
            if current:
                segments.append(current)
                current = []
            continue
        current.append(token)
    if current:
        segments.append(current)
    return segments


def _is_assignment(token: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z_]\w*=.*", token or ""))


def _assignment_parts(token: str) -> tuple[str, str]:
    name, _, value = token.partition("=")
    return name, value


def _is_path_like(token: str) -> bool:
    if not token or any(char.isspace() for char in token):
        return False
    if token in {"-", "--"}:
        return False
    return (
        token.startswith("/")
        or token.startswith("~/")
        or token == "~"
        or token == "."
        or token == ".."
        or token.startswith("./")
        or token.startswith("../")
    )


def _resolve_shell_path(token: str, cwd: str, variables: dict[str, str]) -> str:
    value = token.strip()
    var_match = re.fullmatch(r"\$\{?([A-Za-z_]\w*)\}?", value)
    if var_match:
        value = variables.get(var_match.group(1), value)
    value = os.path.expandvars(os.path.expanduser(value))
    if not os.path.isabs(value):
        value = os.path.join(cwd or os.getcwd(), value)
    return os.path.abspath(value)


def _emit_if_path_like(
    refs: list[LocalPathReference],
    token: str,
    *,
    cwd: str,
    variables: dict[str, str],
    reason: str,
    allow_plain_relative: bool = False,
) -> None:
    raw = token.strip()
    if not raw or raw in {"-", "--"}:
        return
    var_match = re.fullmatch(r"\$\{?([A-Za-z_]\w*)\}?", raw)
    if var_match and variables.get(var_match.group(1)):
        refs.append(LocalPathReference(raw, _resolve_shell_path(raw, cwd, variables), reason))
        return
    if _is_path_like(raw) or allow_plain_relative:
        refs.append(LocalPathReference(raw, _resolve_shell_path(raw, cwd, variables), reason))


def _segment_redirection_refs(segment: list[str], *, cwd: str, variables: dict[str, str]) -> list[LocalPathReference]:
    refs: list[LocalPathReference] = []
    index = 0
    while index < len(segment):
        token = segment[index]
        if token in _REDIRECT_OPERATORS and index + 1 < len(segment):
            target = segment[index + 1]
            expanded_target = os.path.expandvars(os.path.expanduser(target.strip()))
            if expanded_target not in {"/dev/null", os.devnull}:
                _emit_if_path_like(
                    refs,
                    target,
                    cwd=cwd,
                    variables=variables,
                    reason="redirection",
                    allow_plain_relative=True,
                )
            index += 2
            continue
        if token in _FD_REDIRECT_OPERATORS:
            index += 2
            continue
        index += 1
    return refs


def _strip_redirections(segment: list[str]) -> list[str]:
    stripped: list[str] = []
    index = 0
    while index < len(segment):
        token = segment[index]
        if token in _REDIRECT_OPERATORS or token in _FD_REDIRECT_OPERATORS:
            index += 2
            continue
        # shlex separates `2>/dev/null` into `2`, `>`, `/dev/null`.  The
        # standalone fd number is shell syntax, not a command argument.
        if token.isdigit() and index + 1 < len(segment) and segment[index + 1] in (_REDIRECT_OPERATORS | _FD_REDIRECT_OPERATORS):
            index += 1
            continue
        stripped.append(token)
        index += 1
    return stripped


def _iter_non_option_args(parts: list[str]) -> Iterable[str]:
    for arg in parts:
        if not arg or arg == "--":
            continue
        if arg.startswith("-") and arg != "-":
            continue
        yield arg


def _path_args_for_command(head: str, args: list[str]) -> Iterable[str]:
    if head in _PATH_PASSTHROUGH_COMMANDS:
        yield from _iter_non_option_args(args)
        return
    if head == "ls":
        yield from _iter_non_option_args(args)
        return
    if head == "find":
        for arg in args:
            if arg.startswith("-") or arg in {"(", ")", "!"}:
                break
            yield arg
        return
    if head in {"grep", "egrep", "fgrep", "rg"}:
        skipped_pattern = False
        for arg in args:
            if arg == "--":
                continue
            if arg.startswith("-"):
                continue
            if not skipped_pattern:
                skipped_pattern = True
                continue
            yield arg
        return
    if head == "sed":
        skipped_script = False
        for arg in args:
            if arg.startswith("-"):
                continue
            if not skipped_script:
                skipped_script = True
                continue
            yield arg
        return
    if head in _SCRIPT_COMMANDS:
        skip_next = False
        for arg in args:
            if skip_next:
                skip_next = False
                continue
            if arg in {"-c", "-e", "-m"}:
                skip_next = True
                continue
            if arg.startswith("-"):
                continue
            yield arg
            return


def _update_shell_variable(token: str, variables: dict[str, str]) -> None:
    name, value = _assignment_parts(token)
    if _is_path_like(value):
        variables[name] = value


def iter_local_path_references(command: str, *, cwd: str = "") -> list[LocalPathReference]:
    """Return local filesystem references that TerminalTool should validate.

    The parser is intentionally conservative about *where* it looks: it follows
    shell tokens and validates paths used by local filesystem commands or real
    redirections.  It does not regex-scan quoted strings, env var payloads, or
    remote CLI arguments; that prevents false positives for commands that embed
    Android/Linux paths for execution elsewhere.
    """
    current_dir = os.path.abspath(os.path.expanduser(cwd or os.getcwd()))
    variables: dict[str, str] = {}
    refs: list[LocalPathReference] = []

    for raw_segment in _split_shell_token_segments(command):
        refs.extend(_segment_redirection_refs(raw_segment, cwd=current_dir, variables=variables))
        segment = _strip_redirections(raw_segment)
        if not segment:
            continue

        while segment and _is_assignment(segment[0]):
            _update_shell_variable(segment.pop(0), variables)
        if not segment:
            continue

        head = os.path.basename(segment[0]).lower()
        args = segment[1:]

        if head == "export":
            for arg in args:
                if _is_assignment(arg):
                    _update_shell_variable(arg, variables)
            continue

        if head == "cd":
            target = args[0] if args else "~"
            resolved = _resolve_shell_path(target, current_dir, variables)
            refs.append(LocalPathReference(target, resolved, "cd"))
            current_dir = resolved
            continue

        if head in _REMOTE_CLI_HEADS:
            continue

        if head in _LOCAL_PATH_COMMANDS:
            for arg in _path_args_for_command(head, args):
                _emit_if_path_like(
                    refs,
                    arg,
                    cwd=current_dir,
                    variables=variables,
                    reason=head,
                    allow_plain_relative=True,
                )
            continue

        # Unknown local command: validate only obvious standalone path tokens.
        for arg in args:
            _emit_if_path_like(refs, arg, cwd=current_dir, variables=variables, reason=head or "command")

    return refs


def _has_real_file_redirection(command: str) -> bool:
    for segment in _split_shell_token_segments(command):
        refs = _segment_redirection_refs(segment, cwd=os.getcwd(), variables={})
        if refs:
            return True
    return False


def _words_from_cli_tokens(parts: list[str]) -> set[str]:
    words: set[str] = set()
    for token in parts[1:]:
        if token.startswith("-"):
            normalized_flag = token.lstrip("-").replace("_", "-")
            if normalized_flag in {"help", "version"}:
                words.add(normalized_flag)
            continue
        if any(char.isspace() for char in token):
            # Option payloads such as remote `--cmd "kubectl get pods"` are
            # opaque strings, but their verbs still tell us whether the remote
            # operation is read-only or mutating.
            for word in re.findall(r"[A-Za-z][A-Za-z0-9_-]+", token.lower()):
                words.add(word)
            continue
        for word in re.split(r"[^A-Za-z0-9]+", token.lower().replace("_", "-")):
            if word:
                words.add(word)
    return words


def _segment_is_read_only(segment: list[str]) -> bool:
    parts = _strip_redirections(segment[:])
    while parts and _is_assignment(parts[0]):
        parts.pop(0)
    if not parts:
        return True
    head = os.path.basename(parts[0]).lower()
    args = parts[1:]
    if head == "export":
        return True
    if head == "cd":
        return True
    if head == "sed" and any(arg == "-i" or arg.startswith("-i") for arg in args):
        return False
    if head in _READ_ONLY_HEADS:
        if head in {"python", "python3"}:
            return "-c" in args or "-m" in args or not args or all(not _is_path_like(arg) for arg in args)
        return True
    if head in _REMOTE_CLI_HEADS:
        words = _words_from_cli_tokens(parts)
        if words & _MUTATE_LIKE_WORDS and not (words & _READ_LIKE_WORDS):
            return False
        # Remote CLIs often use verbs such as `exec` or `terminal` to perform a
        # read-only inspection inside an isolated device/pod. Treat them as
        # controller read tools unless an explicit mutating verb is present.
        return True
    words = _words_from_cli_tokens(parts)
    return bool(words & _READ_LIKE_WORDS) and not bool(words & _MUTATE_LIKE_WORDS)


def is_read_only_terminal_command(command: str) -> bool:
    """Return True for terminal commands that inspect state without mutation.

    This is used by the controller repeat guard, not by the final TerminalTool
    sandbox.  It keeps multi-step query workflows from being counted as
    duplicate side effects while still rejecting local writes, desktop control,
    installs, process control, and real file redirections.
    """
    if not command:
        return False
    stripped = re.sub(r"\s+\|\|\s+echo\s+.+$", "", command.strip())
    if _has_real_file_redirection(stripped):
        return False
    intents = terminal_command_intents(stripped)
    if intents & {
        "capture_screenshot", "capture_photo", "record_screen", "notify", "open",
        "install", "git_commit", "git_push", "process_control", "destructive_file",
    }:
        return False
    for segment in _split_shell_token_segments(stripped):
        if not _segment_is_read_only(segment):
            return False
    return True


def _local_shell_risk_level(command: str) -> int:
    if not command:
        return 1
    if _has_real_file_redirection(command):
        return 2
    for raw_segment in _split_shell_token_segments(command):
        segment = _strip_redirections(raw_segment)
        while segment and _is_assignment(segment[0]):
            segment.pop(0)
        if not segment:
            continue
        head = os.path.basename(segment[0]).lower()
        args = segment[1:]
        if head in _REMOTE_CLI_HEADS:
            words = _words_from_cli_tokens(segment)
            if words & {"delete", "remove", "rm", "write", "set", "apply", "patch", "install", "uninstall", "push", "commit", "send", "kill", "restart", "reboot"}:
                return 2
            continue
        if head in {"mkfs", "shutdown", "reboot", "fdisk", "parted", "rmdir"}:
            return 3
        if head == "dd":
            return 3
        if head == "rm":
            joined_args = " ".join(args)
            if re.search(r"(^|\s)-[A-Za-z]*r[A-Za-z]*f|(^|\s)-[A-Za-z]*f[A-Za-z]*r", joined_args):
                return 3
            return 2
        if head in {"mkdir", "touch", "cp", "mv", "chmod", "chown", "kill", "pkill"}:
            return 2
        if head in {"pip", "pip3", "npm", "pnpm", "yarn", "brew", "apt-get", "yum"} and "install" in args:
            return 2
        if head == "git" and args and args[0] in {"commit", "push", "add"}:
            return 2
        if head == "sed" and any(arg == "-i" or arg.startswith("-i") for arg in args):
            return 2
        if head == "perl" and any(arg.startswith("-pi") for arg in args):
            return 2
    return 1


def classify_terminal_command(command: str) -> int:
    """Classify shell command risk: 1 safe, 2 needs approval, 3 high risk."""
    shell_level = _local_shell_risk_level(command)
    if shell_level >= 3:
        return 3

    risk_patterns = [
        r":\(\)\{ :|:& \};:",
    ]
    if any(re.search(pattern, command) for pattern in risk_patterns):
        return 3

    if shell_level >= 2:
        return 2

    # Some commands perform a user-visible desktop side effect even when the
    # shell snippet itself does not contain a conventional mutation token such
    # as mkdir/cp/redirection.  Treat these by semantic intent instead of by a
    # growing command allowlist: ExecApprovalService can then approve them only
    # when they match the latest explicit user request, while TerminalTool keeps
    # enforcing the filesystem sandbox.
    desktop_side_effect_intents = {
        "capture_screenshot",
        "capture_photo",
        "record_screen",
        "notify",
        "open",
    }
    if terminal_command_intents(command) & desktop_side_effect_intents:
        return 2
    return 1


def _split_shell_segments(command: str) -> list[list[str]]:
    segments: list[list[str]] = []
    for segment in re.split(r"\s*(?:&&|\|\||;)\s*", command.strip()):
        if not segment:
            continue
        assignment = re.fullmatch(r"[A-Za-z_]\w*=(.+)", segment)
        if assignment:
            # Preserve assignments as a pseudo command so callers can ignore them.
            segments.append(["__assignment__", assignment.group(1)])
            continue
        try:
            parts = shlex.split(segment)
        except ValueError:
            continue
        if parts:
            segments.append(parts)
    return segments


def terminal_command_intents(command: str) -> set[str]:
    """Infer high-level user-facing intents from a terminal command.

    This is intentionally semantic, not an allowlist: it lets the controller
    decide whether a generated command matches the latest explicit user request.
    """
    intents: set[str] = set()
    lowered = command.lower()
    segments = _split_shell_segments(command)
    basenames = [os.path.basename(parts[0]).lower() for parts in segments if parts]

    if "screencapture" in basenames:
        if re.search(r"(^|\s)-v(\s|$)", lowered):
            intents.add("record_screen")
        else:
            intents.add("capture_screenshot")
    if "imagesnap" in basenames:
        intents.add("capture_photo")
    if "ffmpeg" in basenames and any(marker in lowered for marker in ("avfoundation", "/dev/video", "camera", "摄像头")):
        if any(marker in lowered for marker in ("screen", "capture_cursor", "录屏")):
            intents.add("record_screen")
        else:
            intents.add("capture_photo")
    if "osascript" in basenames and "display notification" in lowered:
        intents.add("notify")
    if "open" in basenames:
        intents.add("open")
    if "opencli" in basenames and re.search(r"\bopencli\s+browser\s+open\b", lowered):
        intents.add("open")
    if re.search(r"\b(pip|npm|pnpm|yarn|brew)\s+install\b|\bapt-get\b|\byum\b", lowered):
        intents.add("install")
    if re.search(r"\bgit\s+commit\b", lowered):
        intents.add("git_commit")
    if re.search(r"\bgit\s+push\b", lowered):
        intents.add("git_push")
    if re.search(r"(^|\s)(kill|pkill)\b", lowered):
        intents.add("process_control")
    if _local_shell_risk_level(command) >= 2 or re.search(r"\bwrite_text\b|\bopen\([^)]*,\s*['\"]w", command):
        intents.add("file_mutation")
    if re.search(r"(^|\s)rm\b|\bchmod\b|\bchown\b", lowered):
        intents.add("destructive_file")
    return intents


def user_terminal_intents(text: str) -> set[str]:
    normalized = text.lower()
    intents = {
        intent
        for intent, keywords in TERMINAL_INTENT_KEYWORDS.items()
        if any(keyword in normalized for keyword in keywords)
    }
    if any(keyword in normalized for keyword in BROAD_EXECUTION_KEYWORDS):
        intents.add("broad_execution")
    return intents


def should_auto_approve_terminal_command(command: str, latest_user_text: str) -> bool:
    """Return True when the controller may add approved=True for a command.

    The policy is generic:
    - never auto-approve high-risk commands;
    - only auto-approve commands TerminalTool classifies as approval-required;
    - require semantic alignment between latest user request and command intent;
    - allow broad "run/execute this" wording for non-destructive level-2 commands.
    """
    if classify_terminal_command(command) != 2:
        return False

    command_intents = terminal_command_intents(command)
    user_intents = user_terminal_intents(latest_user_text)
    if not command_intents or not user_intents:
        return False

    sensitive_intents = {"destructive_file", "process_control", "install", "git_push"}
    if command_intents & sensitive_intents:
        return bool((command_intents - {"file_mutation"}) & user_intents)

    direct_intents = command_intents & user_intents
    if direct_intents:
        return True

    if "broad_execution" in user_intents:
        return not (command_intents & {"destructive_file", "process_control", "install", "git_push"})

    return False


def primary_terminal_action(command: str) -> str:
    """Return a stable semantic action for repeat detection, if available."""
    priority: Iterable[str] = (
        "capture_screenshot",
        "capture_photo",
        "record_screen",
        "notify",
        "open",
        "install",
        "git_commit",
        "git_push",
        "process_control",
    )
    intents = terminal_command_intents(command)
    for intent in priority:
        if intent in intents:
            return intent
    return ""
